### ISSUE TITLE
Fourmolu formats code very weirdly

### ISSUE THREAD

**Issue by ad-si** [fourmolu/fourmolu#357] opened 2023-08-16 19:37 UTC
This probably some kind of installation / configuration issue in VSCode.

It currently reformats every

```hs
liftIO $
  withConnection "file.sqlite" $
    \conn -> …
```

to

```hs
liftIO $
  $ withConnection "file.sqlite"
  $ \conn -> …
```

It didn't do that before and I can't even see a setting for this?

When checking the log it says:

```txt
2023-08-16T19:22:05.479706Z | Info | fourmolu: Loaded Fourmolu config from: "/Users/adrian/Projects/XXX/fourmolu.yaml"
```
So that seems to work I guess? Or how do I know if it is even formatted by fourmolu and not something else?

My GHCup setup is:

- ghcup - 0.1.19.4
- stack - 2.11.1
- hls - 2.1.0.0
- cabal - 3.10.1.0
- ghc - 9.4.5

I already tried all the usual stuff: Reinstalling, clearing cache, using an older version of HLS, …
But nothing helps. What is going on?

Sorry that this issue report isn't as comprehensive as I would like it to be, but I can't get it to work and it's really upsetting.

**Comment by brandonchinn178** [comment] 2023-08-16 19:46
I'm sorry to hear that this is frustrating! This can happen if you're working in a module that isn't mentioned in the Cabal file. This was fixed in [Fourmolu 0.13.0.0](https://github.com/fourmolu/fourmolu/blob/main/CHANGELOG.md#ormolu-0710); can you see what version of Fourmolu is bundled in HLS? Can you provide some more information about your Cabal file / how your Cabal project is set up?

**Comment by ad-si** [comment] 2023-08-16 20:59
I'm on haskell-2.4.1, so apparently Fourmolu 0.13 (Added by you 😛 https://github.com/haskell/haskell-language-server/releases/tag/2.1.0.0)

I have a root `stack.yaml` and a `subpackage/package.yaml`.

**Comment by ad-si** [comment] 2023-08-16 21:12
I just installed it globally with `brew install fourmolu` and then I activated the `"haskell.plugin.fourmolu.config.external": true`. Now it works. So it seems to be a problem with the bundled version…

**Comment by brandonchinn178** [comment] 2023-08-16 21:22
ah my PR just added support for fourmolu 0.13, but HLS itself builds with fourmolu 0.12 (see stack.yaml). Can you make an issue in the haskell-language-server repo (or even better, submit a PR to bump the version in stack.yaml)

**Comment by ad-si** [comment] 2023-08-16 21:37
Opened a PR: https://github.com/ad-si/haskell-language-server/pull/1

**Closed** 2023-08-16 23:14 UTC
Labels: bug

**Comment by dariooddenino** [comment] 2023-08-23 08:35
I'm having a very similar issue, the problem is that I had already attempted the solutions listed here without luck.

ghcup - 0.1.19.4
stack - 2.9.3
hls - 2.1.0.0
cabal - 3.10.1.0
ghc - 9.2.8

I have set `"haskell.plugin.fourmolu.config.external": true`

The problem here is that if I format a file using `fourmolu` from the terminal, I get:
```haskell
foo
  $ bar
```
And when I format from an editor using hls (I've tried both vscode and helix) I get:
```haskell
foo $
  bar
```

I'm fairly sure that it's the same exact `fourmolu` executable, using the same config file. 
This is the log from hls:
![Screenshot from 2023-08-23 10-17-59](https://github.com/fourmolu/fourmolu/assets/3266789/2afc91e3-2453-480f-90eb-ebd828646521)

I'm out of ideas and I don't know what else to try. 

Thanks!

**Comment by brandonchinn178** [comment] 2023-08-23 15:16
So the formatting is fine from editors, but not command line? How are you running fourmolu on the command line?

**Comment by dariooddenino** [comment] 2023-08-24 07:08
> So the formatting is fine from editors, but not command line? How are you running fourmolu on the command line?

Thanks for the reply!

I was under the impression that the output from the terminal was the correct one. But it doesn't matter that much, I'd just like them to have the same output.

I'm running fourmolu like this: `fourmolu -i ./`.
It loads the same config file I wrote above.

**Comment by brandonchinn178** [comment] 2023-08-24 15:09
Yes, the correct format is

```hs
foo $
  bar
```

The other format occurs when fourmolu doesnt realize `$` is the `$` function from `base`, so it treats it as a custom infix operator with unknown frequency.

Can you run `fourmolu --version` on the command line? I suspect you have two versions of fourmolu installed: the one visible to HLS is 0.13, the one visible in the terminal is < 0.13

**Comment by dariooddenino** [comment] 2023-08-24 15:12
> Yes, the correct format is
> 
> ```haskell
> foo $
>   bar
> ```
> 
> The other format occurs when fourmolu doesnt realize `$` is the `$` function from `base`, so it treats it as a custom infix operator with unknown frequency. This happens on fourmolu < 0.13 when you dont have a cabal file or the cabal file does not mention the source file.
> 
> Can you run `fourmolu --version` on the command line? I suspect you have two versions of fourmolu installed: the one visible to HLS is 0.13, the one visible in the terminal is < 0.13

It's the same version, I even searched for my filesystem for different versions:
```
❯ fourmolu -v
fourmolu 0.13.1.0
using ghc-lib-parser 9.6.2.20230523
```

The incorrect format it's the same I'm getting from the CI setup in docker, which is explicitly installing `fourmolu-0.13.1.0` :/

**Comment by marcosh** [comment] 2023-08-24 15:35
@brandonchinn178 I'm a colleague of @dariooddenino. I just realised that the issue comes from the usage of `NoImplicitPrelude`. I guess that with it activated, `fourmolu` does not recognise `$` as coming from `base`.

Still, I don't understand why it works differently when used with `hls`

**Comment by brandonchinn178** [comment] 2023-08-24 15:40
Aha! Do you have `import Prelude` or do you have a prelude module you're importing? You'll need to follow the instructions in the README to mention that your custom prelude module reexports Prelude.

I'm not sure why hls is different. It's using the same fourmolu config, right? @georgefst any ideas?

**Comment by marcosh** [comment] 2023-08-24 15:54
> Aha! Do you have `import Prelude` or do you have a prelude module you're importing? You'll need to follow the instructions in the README to mention that your custom prelude module reexports Prelude.

adding the reexport fixed it! Thanks a lot for the tip!
