### ISSUE TITLE
Testing all options

### ISSUE THREAD

**Issue by georgefst** [fourmolu/fourmolu#49] opened 2020-10-13 13:49 UTC
Until recently, all our output options have been binary choices*, with a neat split in to "the Ormolu version" and "the Fourmolu version". Our tests have thus tested our default options, and Ormolu's default options. This was never going to last. #48 is the first to introduce an option which is not used by default.

We have a few choices:
- Run all the tests with all the combinations of options. This may take a long time to run (I haven't tried it yet), and it would start to become difficult to review all the outputs to check that everything looks sensible. But it does give us pretty comprehensive regression tests.
  - Obviously this grows exponentially as we add more options...
- Only test each option on the examples where it should be relevant, e.g. there's no point running with and without `record-brace-space` on a file that doesn't contain any records. Setting this up would require reviewing each test case to determine which options are relevant. We could also miss bugs where an option affects something it shouldn't.
- Consider which options are likely to interact with each other, and filter the set of combinations accordingly. This has some of the same drawbacks as the previous choice.

\* Apart from indentation, but for the purposes of this discussion that's a choice between two and four. There doesn't seem much point testing with any more than that.

**Comment by kbertalan** [comment] 2020-12-19 15:28
@georgefst The current tests are excellent for testing each option separately and isolated. I agree that checking those files with multiple with all possible combinations of options would be hard to maintain.

I think it would also be beneficial to provide few additional test cases, with more complex haskell files with ADTs, records, multiple top level declarations, imports, etc... Setting up those test files would be easy, just use few from the codebase, and maybe simplify if needed.

On these new test files (almost) all option combinations can be checked, if indentation and new lines between declarations have limited set of settings (2 or max 3).

As the number of output files count will be much higher, I advise to encode the options into the file name. An `example.hs` would have `example-i2-cst-iw-rbs-hssl-nbd1.hs` for the ormolu settings, which covers these settings:
* i2 - indent 2
* cst - comma style trailing
* iw - indent wheres enabled
* rbs - record brace space enabled
* diff friendly import export disabled (if enabled it would be `dfie`)
* respectful disabled (if enabled it would be `r`)
* hssl - haddock style single line
* nbd1 - new lines between declarations set to 1

With this approach there would be at least 256 outputs for a single test file, so skipping some combinations still would be needed to reduce the maintenance cost.

Can you comment on this idea?

**Comment by kbertalan** [comment] 2020-12-21 14:58
I have created a fork and experimented with the approach I described above. It is located at https://github.com/kbertalan/fourmolu/tree/testing-all-options

**Comment by georgefst** [comment] 2021-10-30 14:56
We now have a number of open PRs which add options that I don't think we should enable by default (#77, #82, #85, #83, #94, #95, #102, #103, #108). Merging all of them would give us a lot of untested code, so we have to address this issue to some extent. In a sense the cat is already out of the bag with #48, but I'm reluctant to make the situation any worse.

@kbertalan's approach looks reasonable, but it doesn't really address the issue of exponential blowup.

At the very least, for each option, we should run the whole test suite with only that one change to the default options, and check that it has no safety or idempotence issues. Some of the PRs above would unfortunately fail here (e.g. #103).

Is anyone interested in stepping up to implement this simple improvement? Or does anyone have any better ideas?

Tagging the authors of the PRs mentioned above, to apologise for the fact they haven't been merged, and since I'm particularly interested to get their thoughts: @wldhx @Anrock @expipiplus1 @gustavoavena @Player-205 @3kyro.

**Comment by Profpatsch** [comment] 2021-10-31 19:26
Funnily enough, this was exactly the reason why ormolu doesn’t have config options in the first place.

Given that we are talking something super arbitrary (syntax) here, there is beauty in simplicity.

**Comment by georgefst** [comment] 2021-10-31 21:39
> there is beauty in simplicity

Hard to disagree with that! But I think we always knew what ugliness we were getting in to.

**Comment by expipiplus1** [comment] 2021-11-01 03:36
> As the number of output files count will be much higher, I advise to encode the options into the file name. An `example.hs` would have `example-i2-cst-iw-rbs-hssl-nbd1.hs` for the ormolu settings, which covers these settings:

Why not just make the file name `example-title --indent-wheres false --align true --indentation 2.hs`, i.e. after the filename it's just the arguments to a fourmolu invocation. Self explainable and trivial to go from filename to `Config`.

We also only need to check combinations where there is some significant interaction, so for the set I would suggest:

- No options (fourmolu defaults)
- Ormolu defaults
- Everything turned up to 11
- Each option enabled on its own. 
- (if any) specific interactions not covered by the above cases.

**Comment by dpwiz** [comment] 2021-11-12 11:08
There can be an OS limit on how long a file name can be.

This can be ameliorated by using option bundles and a simple naming schema:

- `default`: ormolu defaults (which should be THE default).
- `option-FOO`: exactly one deviation from the default.
- `bundle-BAR`: named option bundles (fourmolu defaults can be one of those), to demonstrate how a bunch of options mesh together.

Bundles can be described in test harness (exotic test cases), hardcoded in (fourmolu style), or simply point to a config file (distributable).

**Comment by georgefst** [comment] 2021-11-15 09:58
>     * `default`: ormolu defaults (which should be THE default).

Does it really matter which is the default? I'd be inclined to use Fourmolu's defaults, seeing as they would then be better tested.

**Comment by dpwiz** [comment] 2021-11-15 14:47
With fourmolu as a complete drop-in replacement with exactly same behaviour (assuming matching versions) it is easier to distribute and use.

And using ormolu defaults keeps a hope of upstreaming alive :pray:

**Comment by georgefst** [comment] 2021-11-15 14:51
Oh! You mean outside the context of testing? That should be opened as a separate issue, but I for one would argue against it.

**Comment by dpwiz** [comment] 2021-11-15 16:57
> You mean outside the context of testing?

Yeah, but with "one-deviation" series it can get confusing about what a default is.

With ormolu as a baseline, the tests can readily showcase all the differences. And with no switches flipped it just reverts to a baseline.

With fourmolu as a baseline, the switches demonstrate not "one at a time", but "some at a time", potentially obscuring the case.

**Comment by wldhx** [comment] 2021-11-16 19:39
So there's some work on the subject in #129.

I'd initially tried @expipiplus1's suggestion, but ran into a file length limit of 255 -- a problem, turns out, with our options as they are, never mind adding more.
@kbertalan has apparently foreseen this with their abbreviation approach :)

I decided to favor the style discussed recently though. The PR tests every option in isolation, and makes the idea of "bundles" (as suggested by @dpwiz) more explicit with an eye towards actually using it as we start merging the PR backlog in.

**Comment by gustavoavena** [comment] 2021-11-19 09:26
@georgefst , I had added test cases to the new option I introduced in my PR (#102), but I think that the process of adding tests could be a bit easier... So yesterday I spent some time refactoring the `PrinterSpec` module to make it easier to add tests for new combinations of options.

I put up #132 with the changes and would love to get some feedback on it.

It doesn't implement the approach suggested by @kbertalan, but I think it's a step in the right direction...

**Comment by brandonchinn178** [comment] 2022-04-16 20:58
First of all, sorry to everyone for the lack of communication. There's been a bit of uncertainty among the maintainers exactly what we want for the future of Fourmolu / testing / etc. which is why we've been leaving so many things untouched lately. George recently decided to take a bit of a step back from Fourmolu, so I'll be taking a bit more of an involved role, which also means revisiting a lot of these core decisions.

Secondly (and most importantly), I really want to thank everyone for their patience + work they've put into this issue; I cannot underscore this enough. Especially @wldhx and @gustavoavena for all the work you've put into #129 and #132. Please understand that we don't take your effort lightly, and we really appreciate your contributions, both to this issue and also to any future contributions to this project.

As I get more familiar with this project, and after reviewing the PRs currently up, I think we want to go a slightly different route with testing. This is in no way a fault of the authors of those PRs; I think the way this issue was originally written guided conversation along a trajectory that is not ideal for this project. Specifically, the original issue implied building upon the existing test suite, and the PRs showed the natural consequence of that: #129 adds about 400 new files for every option (for a total of 4000 new files), and #132, while it doesn't add files immediately, provides a framework intended to do the same as #129: adding 400 files for every set of options. Ultimately, it comes down to this: **no one's going to be auditing 400 new files in a code review for a PR that adds a new config flag**. True, those files will effectively act as regression tests (i.e. "golden" tests), preventing accidental changes in the future, but they aren't suitable for checking that the feature _works as intended right now_. Having 400 files per option just won't scale, and it's a rather heavy cost to the repo size just for regression testing.

Here's what I'm thinking, instead:
1. `PrinterSpec.hs` runs all the examples in `data/` against ormolu options and fourmolu options
    1. Revert it basically back to the way this file is in Ormolu, except also running against default fourmolu options
    2. Remove any `data/` files that was added in Fourmolu that's not in Ormolu
2. Add a `data/fourmolu/` folder with:
    1. `extras/` folder for extra files with extra regressions we want to test against (just so we can keep track of what tests are ours and what tests are ormolu's)
        * These regressions are candidates for moving upstream to Ormolu, and we can hopefully keep this folder to a minimal number of files
    2. A folder for each config flag (`indentation/`, `comma-style/`, etc.) that contains a test file with a representative example of that config flag, which generates files for each config flag option, e.g. `comma-style/input.hs`, `comma-style/output-leading.hs`, and `comma-style/output-trailing.hs`

This definitely won't be as comprehensive as running the tests on all the example files, but I think it's a good compromise to bridge the current testing gap. If regressions or issues come up, we'll just add the example to the test file for the relevant flag (or add to `extras/`) and move on.

I'll be working on a branch implementing this, and hopefully we can start getting the long list of PRs using the new test framework + merged. If you're onboard with this plan, please add a thumbs-up reaction to this comment; if anyone has any strong objections to this, please add a comment and I'll address it before merging my branch.

**Comment by tchoutri** [comment] 2022-04-16 21:08
@brandonchinn178 Thanks a lot for the communication! :)

**Closed** 2022-05-30 21:35 UTC
Labels: help wanted
