### ISSUE TITLE
Multiple AST difference errors when formatting large code base.

### ISSUE THREAD

**Issue by jonathanknowles** [fourmolu/fourmolu#241] opened 2022-10-14 07:44 UTC
## Is your bug specific to Fourmolu?
- [x] Yes, I've verified that Ormolu does not have this bug

## Describe the bug

We're attempting to use `fourmolu` version `0.8.2.0` to reformat [this repository](https://github.com/input-output-hk/cardano-wallet), which contains around 400 Haskell source files and around 200,000 lines of code.

When using `fourmolu` with its default options (i.e., without any `fourmolo.yaml` configuration file), `fourmolu` produces multiple "AST of input and AST of formatted code differ" errors.

In particular, the error output seems to indicate that `fourmolu` is attempting to insert spaces between `@` symbols and types (use of `TypeApplications`):

```diff
-         let accountPath = Link.postAccountKey @'Shelley w (DerivationIndex $ 2147483648 + 1)                                                                                        
+         let accountPath = Link.postAccountKey @ 'Shelley w (DerivationIndex $ 2147483648 + 1)                                                                                       
```

These AST errors do not appear when using `ormolu`.

## Information

- Branch reformatted with `ormolu`: [cardano-wallet/jonathanknowles/ormolu](https://github.com/input-output-hk/cardano-wallet/compare/master...jonathanknowles/ormolu)
- Log of the error output from `fourmolu`: [fourmolu.log](https://github.com/fourmolu/fourmolu/files/9783553/fourmolu.log)
- Command used to invoke `fourmolu`:
    ```sh
    fourmolu --mode inplace $(git ls-files '*.hs')
    ```
- `ormolu` version:
    ```sh
    $ ormolu --version
    ormolu 0.1.4.1 UNKNOWN UNKNOWN
    using ghc-lib-parser 8.10.7.20210828
   ```
- `fourmolu` version:
    ```sh
    $ fourmolu --version
    fourmolu 0.8.2.0 UNKNOWN UNKNOWN
    using ghc-lib-parser 9.2.4.20220729
    ```
- `ghc` version:
    ```sh
    $ ghc --version
    The Glorious Glasgow Haskell Compilation System, version 8.10.7
    ```
- `cabal` version:
    ```sh
    $ cabal --version
    cabal-install version 3.6.2.0
    compiled using version 3.6.2.0 of the Cabal library
    ```

Could it be that we are using `fourmolo` incorrectly?

If I can provide any further info, please let me know. I'd be very happy to help with debugging this issue. Many thanks!

**Comment by ocharles** [comment] 2022-10-14 07:51
I think this is a duplicate of https://github.com/fourmolu/fourmolu/issues/211.

**Comment by brandonchinn178** [comment] 2022-10-14 15:02
Yes, the bug you described is a duplicate. Please make separate tickets for each specific class of bug you find, and make sure you search for existing issues first.

**Closed by brandonchinn178** 2022-10-14 15:02 UTC
Labels: bug

**Comment by jonathanknowles** [comment] 2022-10-15 05:16
Hi @brandonchinn178, @ocharles 

> I think this is a duplicate of https://github.com/fourmolu/fourmolu/issues/211.
> Yes, the bug you described is a duplicate. Please make separate tickets for each specific class of bug you find, and make sure you search for existing issues first.

My apologies, I hadn't spotted that there was a similar bug report. 🙇🏻 

I'll have a further look through the logs and check that there are no other unrelated issues. If there are, I'll create specific bug reports for those (unless similar bug reports already exist).

Many thanks again for your time!

**Comment by brandonchinn178** [comment] 2022-10-15 05:20
No worries! Thanks for taking the time to report! Looking forward to hearing about your experience with fourmolu
